### ISSUE TITLE
More informative error messages in Flexi_ETL()

### ISSUE THREAD

**Issue by ellisp** [nz-mbie/mbieDBmisc-r-package#10]
See https://github.com/nz-mbie/disseminate_rtes/issues/27 - The error message "Some of desc not in data frame" could be better as something like "Some of the Classification descriptions are not columns in the data frame @Dataseries_Name" - or something along those lines.

**Comment by HaizhenWu** [comment]
The new version of mbieDBmisc will solve the issue.
