### ISSUE TITLE
One of the ITM series has gone missing?

### ISSUE THREAD

**Issue by ellisp** [nz-mbie/mbieDBmisc-r-package#14]
This code from the examples in the `ImportTS2` helpfiles:

```
itmdemo <- ImportTS2(TRED, "Short-term NZ traveller departures by EVERY country of main dest and purpose (Monthly)")
```
no longer works.  If it's legitimately gone from the database we just need to change the examples.

If it's not legitimately gone, then something more serious is wrong...

**Comment by ellisp** [comment]
Looks like it's just changed it's name to `NZ-resident traveller departures by EVERY country of main dest and purpose (Monthly)` so we just need to change the example in the helpfile.

Here's some code that helps work out what happened.  it's dataseries 29:

```R
TRED <- odbcConnect("TRED_Prod")
dataset <- sqlFetch(TRED, "timeseries.dataset")
View(dataset[grepl("traveller departures by EVERY country", dataset$Dataset), ])
```

**Comment by HaizhenWu** [comment]
We can make the example more future-proof by grabbing the dataset name from dataset ID (=29).

**Comment by ellisp** [comment]
True, except I want to train people to include the name in the code generally speaking, so the code is self-documenting.  I hadn't been counting on the names changing though.  In general, I'd rather more easily readable code and trade off that we have to fix it every now and then - it's probably good to pay attention when they change the names anyway.

**Comment by HaizhenWu** [comment]
Understood. I have changed the series name to "NZ-resident traveller departures by EVERY country of main dest and purpose (Monthly)".
