### ISSUE TITLE
Function or view to conveniently extract common views of tourism datasets (starting with RTEs)

### ISSUE THREAD

**Issue by ellisp** [nz-mbie/mbieDBmisc-r-package#5]
I find myself unable to let go of

```R
data(RTEs)
```
because the alternative in SQL, particularly the concording of TA_mod to RTO, TA and Region, is far to long to remember.

Could you either build a view in the playpen.dbo. that basically is the same as RTEs; or an R function that wraps around the SQL.  If the latter, give it a general name like

```R
mbieDBmisc::ImportTourism(dataset = "RTEs")
```
that could be generalised to other common views of datasets.  Wouldn't want to do this for every one, but for something like the RTEs that we will nearly always want to concord in this way, could be very useful.

This ties into @shaunmcgirr's queries too.  I'm not ready yet for us to fill up PlayPen or TRED with stacks of Views that in effect form a whole new analytical layer, but we could experiment a little and see what we find useful.

**Comment by shaunmcgirr** [comment]
Agreed, filling up your existing databases (which each do exactly one thing very well) with other "meanings" of the data is an anti-pattern to avoid. When we see customers do it they usually fail to create a coherent 'analytical layer' and instead just get chaos, which is worse than where they started.

So proving the concept on your data(RTEs) use-case is a good approach: see what might work and then pause to generalise. My head (and our existing open-source toolkit) is brimming with ideas on how to regularise and govern the production of such views: I've been reluctant to suggest them until a solid use-case came along. @ellisp let me know if/when you want more input on those (presumably after @HaizhenWu has a shot).

**Comment by HaizhenWu** [comment]
We could create Views on PlayPen first, and then wrap them into `mbieDBmisc::ImportTourism()`. This will provide two access approaches, and make the `mbieDBmisc::ImportTourism()` tidier. 

For views, either we can follow the naming convention `dbo.TourismDatasets_RTEs`, or create a schema `TourismDatasets` such that the Tables/Views will become `TourismDatasets.RTEs` etc.

I didn't find the script which created RTEs in {mbiedata}. I will ask the team if there is any existing SQL code available.

**Comment by ellisp** [comment]
the code that creates it is in create_RTEs project (under regional estimation).  I'm not sure if @RABurson has got round to updating it to draw on TRED.Classifications (as it should) or if it's still using various scary standalone .rda files for classifications.

**Comment by HaizhenWu** [comment]
@RABurson has sent me the code with TRED.Classifications having been incorporated. 

I will create `dbo.TourismDatasets_RTEs` (View name) in mbieDBmisc-R-package project (establish a integrate.r and ./create_TourismDatasets/RTEs.r to do so.

I will create a SQL folder to save the SQL code only, and create_TourismDatasets/RTEs.r will call the SQL code in ./SQL to create View.

**Comment by HaizhenWu** [comment]
The package {mbieDBmisc} project repo has been updated: ImportTourism() added and version lifted to 0.6.8. 

```r
> ImportTourism(Dataset = "RTEs") %>% head
      Type   Origin       Product        Region               RTO          Territorial_Authority YEMar   Spend
1 Domestic Auckland Accommodation      Auckland      Auckland RTO                       Auckland  2009  0.2852
2 Domestic Auckland Accommodation Bay of Plenty Bay of Plenty RTO                  Tauranga City  2009 10.8735
3 Domestic Auckland Accommodation Bay of Plenty Bay of Plenty RTO Western Bay of Plenty District  2009  1.3970
4 Domestic Auckland Accommodation Bay of Plenty      Gisborne RTO               Opotiki District  2009  0.3960
5 Domestic Auckland Accommodation Bay of Plenty Kawerau-Whakatane               Kawerau District  2009  0.0408
6 Domestic Auckland Accommodation Bay of Plenty Kawerau-Whakatane             Whakatane District  2009  1.7828
> ImportTourism(Dataset = "RTEs") %>% dim
[1] 68154     8
```

SQL view PlayPen.dbo.TourismDatasets_RTEs created, and the dataset can be extracted from the view.
![image](https://cloud.githubusercontent.com/assets/7629127/8949266/08617108-3605-11e5-9f7f-96f9a1ac508e.png)

SQL code which extracts data from TRED is stored in mbieDBmisc-R-package/SQL/extracting_TourismDatasets_RTEs.sql and can be used as well.

If the results look OK, the package is ready for peer review.

**Comment by ellisp** [comment]
Looks great and gives the same results as data(RTEs).  I tweaked the helpfile but haven't deployed; can you do that tomorrow then we can close this issue for now and see whether we think this is useful.

**Comment by HaizhenWu** [comment]
Have deployed it to "P:/R/libraries/3.1.2-20150624/" and "P:/R/libraries/3.1.2-20150507".  Could you please delete "P:/R/libraries/3.1.2-20150710/mbieDBmisc" and copy the new one from  "P:/R/libraries/3.1.2-20150624/"? - permission issue again.

I will close this issue.

**Comment by shaunmcgirr** [comment]
This is so awesome! Once my IVS report work is finished @HaizhenWu I imagine it will be easy to adapt my R treatment of each IVS question in to the same framework, if @ellisp wants it.

@James-Hogan have you seen this? Is there a subset of the users you are out and about talking to who could consume data at this level? (ie not scary microdata, but more detail than published)
